# Generated by Django 3.0.6 on 2020-05-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_auto_20200507_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
